import asyncio

from EdgeGPT import Chatbot, ConversationStyle


async def main():

    banks = """RBL Basic Savings Account.
IDFC First Bank Pratham Savings Account.
IndusInd Bank Indus Online Savings Account.
YES Bank Smart Salary Advantage.
Utkarsh Basic Savings Bank Deposit Account ( BSBDA ).
AU Digital Savings Account.
Kotak Mahindra Bank 811 Digital Bank Account.
HDFC Bank BSBDA.
Standard Chartered Bank Aasaan.
State Bank of India BSBDA.
Jupiter Money Bank Account.
Fi money Bank Account."""

    banks = banks.split("\n")

    for bank in banks:


        bot = await Chatbot.create(
        cookies=[
            {
                "domain": ".bing.com",
                "expirationDate": 1716232526.352051,
                "hostOnly": False,
                "httpOnly": False,
                "name": "SnrOvr",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "X=rebateson",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719168239.631044,
                "hostOnly": False,
                "httpOnly": False,
                "name": "SRCHUSR",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "DOB=20230519&T=1684608237000&POEX=W",
            },
            {
                "domain": "www.bing.com",
                "expirationDate": 1684611925,
                "hostOnly": True,
                "httpOnly": False,
                "name": "ai_session",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_AI_SESSION",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1684646513.41907,
                "hostOnly": False,
                "httpOnly": True,
                "name": "SUID",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "A",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719170125.689926,
                "hostOnly": False,
                "httpOnly": False,
                "name": "SRCHHPGUSR",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "SRCHLANG=en&PV=14.0.0&BRW=W&BRH=S&CW=1347&CH=560&SCW=1347&SCH=678&DPR=1.4&UTC=330&DM=0&HV=1684610126&PRVCW=1347&PRVCH=678&EXLTT=31&cdxtone=Creative&cdxtoneopts=h3imaginative,clgalileo,gencontentv3&cdxwinturn=1",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719166913.55946,
                "hostOnly": False,
                "httpOnly": False,
                "name": "ANON",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_ANON",
            },
            {
                "domain": "www.bing.com",
                "expirationDate": 1716146125.406268,
                "hostOnly": True,
                "httpOnly": False,
                "name": "MicrosoftApplicationsTelemetryDeviceId",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_TELEMETRY_ID",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "_SS",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "SID=REDACTED_BING_SID&R=3315&RB=3315&GB=0&RG=4000&RP=3315&PC=U531&OCID=MK12LS",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "ipv6",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "hit=1684611839817&t=4",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "dsc",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "order=ShopOrderDefault",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1685816513.559426,
                "hostOnly": False,
                "httpOnly": False,
                "name": "_U",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_COOKIE_U",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719068526.749352,
                "hostOnly": False,
                "httpOnly": False,
                "name": "SRCHD",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "AF=Z9FD1",
            },
            {
                "domain": "www.bing.com",
                "expirationDate": 1684696180.579731,
                "hostOnly": True,
                "httpOnly": False,
                "name": "GC",
                "path": "/",
                "sameSite": None,
                "secure": False,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_GC",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719068530.224921,
                "hostOnly": False,
                "httpOnly": False,
                "name": "PPLState",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "1",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1687156294,
                "hostOnly": False,
                "httpOnly": False,
                "name": "ANIMIA",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "FRE=1",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1718204527.749233,
                "hostOnly": False,
                "httpOnly": True,
                "name": "_EDGE_V",
                "path": "/",
                "sameSite": None,
                "secure": False,
                "session": False,
                "storeId": None,
                "value": "1",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "NAP",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "V=1.9&E=1c00&C=rTfaZSMEjW6Ycxj6Rs40mifYq4byljNyUThDUSITZJE97nn1c9Jm-A&W=3",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1716232526.351889,
                "hostOnly": False,
                "httpOnly": False,
                "name": "_RwBf",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "ilt=1&ihpd=1&ispd=0&rc=3315&rb=3315&gb=0&rg=4000&pc=3315&mtu=0&rbb=0.0&g=0&cid=&clo=0&v=33&l=2023-05-20T07:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&o=16&p=BINGTRIAL5TO250P201808&c=MY00IA&t=1389&s=2022-09-04T05:59:30.4793970+00:00&ts=2023-05-20T19:15:25.7247713+00:00&rwred=0&wls=2&lka=0&lkt=0&TH=&r=1&mta=0&e=BZX9BrUpZjB_Y02TtrlWgoR0C6ppPs1jlMlUwWYIAixIXnP3pXLTno44r_0ylctlEgTmWfF_PfWudMMbi1RR7A&A=",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719170125.012722,
                "hostOnly": False,
                "httpOnly": False,
                "name": "_UR",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "QS=0&TQS=0",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": True,
                "name": "_EDGE_S",
                "path": "/",
                "sameSite": None,
                "secure": False,
                "session": True,
                "storeId": None,
                "value": "F=1&SID=REDACTED_BING_SID&mkt=en-IN&ui=en-us",
            },
            {
                "domain": "www.bing.com",
                "expirationDate": 1718306128.508824,
                "hostOnly": True,
                "httpOnly": True,
                "name": "MUIDB",
                "path": "/",
                "sameSite": None,
                "secure": False,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_MUID",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719170124.519016,
                "hostOnly": False,
                "httpOnly": True,
                "name": "USRLOC",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "HS=1&ELOC=LAT=28.697607040405273|LON=77.45272827148438|N=Ghaziabad%2C%20Uttar%20Pradesh|ELT=2|&DLOC=LAT=28.697606249999996|LON=77.45272625000001|A=0|N=Ghaziabad%2c+Ghaziabad|C=|S=|TS=230520191216|ETS=230520192523|&CLOC=LAT=28.699505585511247|LON=77.44712783531287|A=733.4464586120832|TS=230520191208|SRC=W",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719170125.322246,
                "hostOnly": False,
                "httpOnly": False,
                "name": "_HPVN",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_HPVN",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719068530.22495,
                "hostOnly": False,
                "httpOnly": True,
                "name": "KievRPSSecAuth",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_COOKIE_KievRPSSecAuth",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719112271.080777,
                "hostOnly": False,
                "httpOnly": False,
                "name": "MMCASM",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "ID=4132FD88076F4576922B548DBD8E5A61",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "msau",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "REDACTED_BING_MSAU",
            },
            {
                "domain": "www.bing.com",
                "hostOnly": True,
                "httpOnly": False,
                "name": "MSCC",
                "path": "/",
                "sameSite": None,
                "secure": False,
                "session": True,
                "storeId": None,
                "value": "1",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1684689719,
                "hostOnly": False,
                "httpOnly": False,
                "name": "MSCC",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "NR",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1718204527.749005,
                "hostOnly": False,
                "httpOnly": False,
                "name": "MUID",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_MUID",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "SRCHS",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "PC=U531",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719068526.749399,
                "hostOnly": False,
                "httpOnly": False,
                "name": "SRCHUID",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "V=2&GUID=0E14CD736D5445D3B7B8E890FB93EAC7&dmnchg=1",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1719168631.360747,
                "hostOnly": False,
                "httpOnly": False,
                "name": "TOptOut",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "1",
            },
            {
                "domain": ".bing.com",
                "expirationDate": 1685718131.606653,
                "hostOnly": False,
                "httpOnly": True,
                "name": "WLID",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": False,
                "storeId": None,
                "value": "REDACTED_BING_WLID",
            },
            {
                "domain": ".bing.com",
                "hostOnly": False,
                "httpOnly": False,
                "name": "WLS",
                "path": "/",
                "sameSite": "no_restriction",
                "secure": True,
                "session": True,
                "storeId": None,
                "value": "REDACTED_BING_WLS",
            },
        ]
    )
        p = f"""Answer these questions in the markdown table for the {bank}. what is the :
1. Interest rates - for the savings account up to 1 lakh and for fixed deposits for the 1 year.
2. ATM charges for cash withdrawal and balance inquiry and debit card charges.
3. number of branches, atm, and employees.
4. checkbook charges and passbook charges.
6.  SMS alert charges.
7.  Net banking charges, mobile banking charges, and UPI charges."""

# {'type': 2, 'invocationId': '0', 'item': {'messages': [{'text': 'Hello world', 'author': 'user', 'from': {'id': '914798687571389', 'name': None}, 'createdAt': '2023-05-20T19:17:12.3874751+00:00', 'timestamp': '2023-05-20T19:17:12.3835604+00:00', 'locale': 'en-us', 'market': 'en-us', 'region': 'us', 'messageId': '44de2675-148f-42ae-9878-4cce12ee6a63', 'requestId': '44de2675-148f-42ae-9878-4cce12ee6a63', 'nlu': {'scoredClassification': {'classification': 'DEEP_LEO', 'score': None}, 'classificationRanking': [{'classification': 'DEEP_LEO', 'score': None}], 'qualifyingClassifications': None, 'ood': None, 'metaData': None, 'entities': None}, 'offense': 'None', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'cib', 'privacy': None, 'inputMethod': 'Keyboard'}, {'text': 'Hello, this is Bing. Welcome to the chat mode. 😊', 'author': 'bot', 'createdAt': '2023-05-20T19:17:17.2330281+00:00', 'timestamp': '2023-05-20T19:17:17.2330281+00:00', 'messageId': '5daab80a-f799-410d-a651-038de82d1550', 'requestId': '44de2675-148f-42ae-9878-4cce12ee6a63', 'offense': 'None', 'adaptiveCards': [{'type': 'AdaptiveCard', 'version': '1.0', 'body': [{'type': 'TextBlock', 'text': 'Hello, this is Bing. Welcome to the chat mode. 😊\n', 'wrap': True}]}], 'sourceAttributions': [], 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None, 'suggestedResponses': [{'text': 'What can you do?', 'author': 'user', 'createdAt': '2023-05-20T19:17:20.7081596+00:00', 'timestamp': '2023-05-20T19:17:20.7081596+00:00', 'messageId': 'c753684e-322d-43a5-abe3-749459a0700b', 'messageType': 'Suggestion', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None}, {'text': 'Tell me a story.', 'author': 'user', 'createdAt': '2023-05-20T19:17:20.7081611+00:00', 'timestamp': '2023-05-20T19:17:20.7081611+00:00', 'messageId': '1529a1d6-cad9-4e97-9087-7331f1204a41', 'messageType': 'Suggestion', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None}, {'text': 'Show me a picture of a cat.', 'author': 'user', 'createdAt': '2023-05-20T19:17:20.7081615+00:00', 'timestamp': '2023-05-20T19:17:20.7081615+00:00', 'messageId': 'b9dbf42d-ee09-41b0-a524-7ba255fd02f7', 'messageType': 'Suggestion', 'offense': 'Unknown', 'feedback': {'tag': None, 'updatedOn': None, 'type': 'None'}, 'contentOrigin': 'DeepLeo', 'privacy': None}]}], 'firstNewMessageIndex': 1, 'defaultChatName': None, 'conversationId': '51D|BingProd|CD7E11F8AC8F45AADBBCE2A726BA4E2BF214B234BCA6172D42B1186B79C27A71', 'requestId': '44de2675-148f-42ae-9878-4cce12ee6a63', 'conversationExpiryTime': '2023-05-21T01:17:21.2164425Z', 'shouldInitiateConversation': True, 'telemetry': {'metrics': None, 'startTime': '2023-05-20T19:17:12.3836435Z'}, 'throttling': {'maxNumUserMessagesInConversation': 20, 'numUserMessagesInConversation': 1}, 'result': {'value': 'Success', 'serviceVersion': '20230519.42'}}}
        response =       await bot.ask(
            prompt=p, conversation_style=ConversationStyle.creative
        )

        print(response)

        reply = response["item"]["messages"][1]["text"]

        print(reply)

        with open("a.txt", "a") as f:

            f.write(f"{bank} : {reply}\n")



    await bot.close()


if __name__ == "__main__":
    asyncio.run(main())
